# Machine Learning vs Deep Learning - Same Use Case

## Prepare Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('../data-sets/Churn_Modelling.csv')

In [3]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
# Encoding categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:,2])

In [6]:
X # After encoding

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
# Train-Test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [8]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Classic Machine Learning

In [9]:
# Decision Tree classifier
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)
pred = clf.predict(X_test)


# Confusion Matrix, Accuracy Score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, pred)
score = accuracy_score(y_test, pred)
print('cm:', cm, '    accuracy_scpre:', score*100)

cm: [[1373  222]
 [ 179  226]]     accuracy_scpre: 79.95


In [10]:
# Random Forest classifier
from sklearn.ensemble import RandomForestClassifier

clf2 = RandomForestClassifier(n_estimators=100)
clf2.fit(X_train, y_train)
pred2 = clf2.predict(X_test)

In [11]:
# Confusion Matrix / Accuracy Score
cm2 = confusion_matrix(y_test, pred2)
score2 = accuracy_score(y_test, pred2)
print('cm:', cm2, '    accuracy_scpre:', score2*100)

cm: [[1529   66]
 [ 209  196]]     accuracy_scpre: 86.25


In [12]:
# %pip install tensorflow-macos

## Artificial Neural Network

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
print(tf.__version__)
print(tf.keras.__version__)

2.16.2
3.13.2


In [15]:
# # Initialising the ANN
# classifier = Sequential()
# #units: It's an art, comes by experience, input+output/2
# #initializer: how your weights are updated
# #relu activation function
# #input_dim: input shape (shape of the data, how many features do we have in the data)
# # Adding the input layer and the first hidden layer
# classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 10))

# # Adding the second hidden layer
# classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# # Adding the third  hidden layer
# classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# # Adding the output layer
# classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

classifier = Sequential([
    Input(shape=(10,)),  # 10 features
    Dense(6, activation='relu'),
    Dense(6, activation='relu'),
    Dense(6, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [16]:
len(X_train)

8000

In [17]:
import numpy as np
y = np.asarray(y_train).reshape(-1)
baseline = max(y.mean(), 1 - y.mean())
print("Majority-class baseline accuracy:", baseline)

Majority-class baseline accuracy: 0.796


In [18]:
# Compiling the ANN 
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
y_train[0]

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 200)

Epoch 1/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 615us/step - accuracy: 0.7936 - loss: 0.4974
Epoch 2/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - accuracy: 0.7960 - loss: 0.4393
Epoch 3/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - accuracy: 0.8035 - loss: 0.4244
Epoch 4/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.8269 - loss: 0.4156
Epoch 5/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 539us/step - accuracy: 0.8305 - loss: 0.4062
Epoch 6/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step - accuracy: 0.8339 - loss: 0.3975
Epoch 7/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 556us/step - accuracy: 0.8346 - loss: 0.3892
Epoch 8/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.8354 - loss: 0.3841
Epoch 9/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.8372 - loss: 0.3808
Epoch 10/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 541us/step - accuracy: 0.8405 - loss: 0.3765
Epoch 11/200
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.8435 - loss: 0.3740
Epoch 12/200
800/80

In [19]:
# Part 3 - Making predictions and evaluating the model
# Predicting the Test set results
y_pred_ann = classifier.predict(X_test)
y_pred_ann = (y_pred_ann > 0.5)

cm3 = confusion_matrix(y_test, y_pred_ann)
print(cm3)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 713us/step
[[1499   96]
 [ 191  214]]


In [20]:
# Making the Confusion Matrix
from sklearn.metrics import accuracy_score

score3 = accuracy_score(y_test,y_pred_ann)
print(score3*100)

85.65


## Hyperparamter Optimization

Run smaller tests first because these can be very expensive computationally.

### Grid Search

In [21]:
# Predict a single observation

"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""

new_prediction = classifier.predict(sc.transform(np.array([[600, 0, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)
new_prediction

# Making the Confusion Matrix
#from sklearn.metrics import confusion_matrixx
#cm = confusion_matrix(y_test, y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[False]])

In [ ]:
import time
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, Dropout

def build_classifier():
    model = Sequential([
        Input(shape=(10,)),
        Dense(12, activation="relu"),
        Dropout(0.25),

        Dense(12, activation="relu"),
        Dropout(0.25),

        Dense(6, activation="relu"),

        Dense(1, activation="sigmoid")
    ])
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    return model

classifier = KerasClassifier(model=build_classifier, verbose=0)

parameters = {
    "batch_size": [10, 20, 100],
    "epochs": [5, 6, 10, 20],
    "loss": ['binary_crossentropy', 'categorical_crossentropy'],
    "optimizer": ['adam', 'rmsprop']

}

grid_search = GridSearchCV(
    estimator=classifier,
    param_grid=parameters,
    scoring="accuracy",
    cv=5,
    n_jobs=1
)

#start timer
start_time = time.time()

grid_search.fit(X_train, y_train)

#End timer
end_time = time.time()
elapsed_time = end_time - start_time

print(grid_search.best_params_)
print(grid_search.best_score_)
print(f"\nExecution time: {elapsed_time:.2f} seconds ({elapsed_time/60:.2f} minutes)")



In [24]:
%pip install scikeras

Note: you may need to restart the kernel to use updated packages.


## Improving the performance of ANN

1. Increase the number of hidden layers
2. Increase number or epochs
3. FIne-tuning the parameters - optimizers, batch_size, epochs
4. Dropout regularization: Dropout(0.25)

Overfitting problem: training accuracy increases, but test accuracy is low